FROM registry.fedoraproject.org/fedora-toolbox:39

RUN dnf -y install make meson vim gcc g++ flex bison bc dtc lzop git-email
RUN dnf -y install glib2-devel pixman-devel SDL2-devel ncurses-devel libslirp-devel
RUN dnf -y install numactl-devel cmake
RUN dnf -y install pinentry-gnome3
RUN dnf -y install python3-pexpect python3-sphinx

RUN dnf clean all

CMD /bin/sh
